-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 14:00:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema venda_de_produtos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema venda_de_produtos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venda_de_produtos` DEFAULT CHARACTER SET utf8 ;
USE `mvenda_de_produtos` ;

-- -----------------------------------------------------
-- Table `venda_de_produtos`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_de_produtos`.`categorias` (
  `idcategorias` INT NOT NULL,
  `dscategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_de_produtos`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_de_produtos`.`produtos` (
  `idprodutos` INT NOT NULL,
  `dsproduto` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `qtdade` INT NOT NULL,
  `foto` LONGBLOB NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idprodutos`, `dsproduto`),
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `venda_de_produtos`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_de_produtos`.`pedidoitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_de_produtos`.`pedidoitens` (
  `idpedidoitens` INT NOT NULL,
  `qtdade` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  `produtos_dsproduto` INT NOT NULL,
  PRIMARY KEY (`idpedidoitens`),
  CONSTRAINT `fk_pedidoitens_produtos1`
    FOREIGN KEY (`produtos_idprodutos` , `produtos_dsproduto`)
    REFERENCES `venda_de_produtos`.`produtos` (`idprodutos` , `dsproduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_de_produtos`.`clintes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `myvenda_de_produtos`.`clintes` (
  `idclintes` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idclintes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venda_de_produtos`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `venda_de_produtos`.`pedidos` (
  `idpedidos` INT NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `sessao` VARCHAR(45) NOT NULL,
  `clintes_idclintes` INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  CONSTRAINT `fk_pedidos_clintes1`
    FOREIGN KEY (`clintes_idclintes`)
    REFERENCES `venda_de_produtos`.`clintes` (`idclintes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
