-- MySQL Script generated by MySQL Workbench
-- Mon Sep 16 14:56:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vendaProduto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vendaProduto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vendaProduto` DEFAULT CHARACTER SET utf8 ;
USE `vendaProduto` ;

-- -----------------------------------------------------
-- Table `vendaProduto`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaProduto`.`categorias` (
  `idcategorias` INT NOT NULL,
  `dscategoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategorias`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mvendaProduto`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaProduto`.`produtos` (
  `idprodutos` INT NOT NULL,
  `dsproduto` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  `qtdade` INT NOT NULL,
  `foto` LONGBLOB NOT NULL,
  `categorias_idcategorias` INT NOT NULL,
  PRIMARY KEY (`idprodutos`, `dsproduto`),
  CONSTRAINT `fk_produtos_categorias`
    FOREIGN KEY (`categorias_idcategorias`)
    REFERENCES `vendaProduto`.`categorias` (`idcategorias`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendaProduto`.`clintes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaProduto`.`clintes` (
  `idclintes` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idclintes`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendaProduto`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaProduto`.`pedidos` (
  `idpedidos` INT NOT NULL,
  `date` DATE NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `sessao` VARCHAR(45) NOT NULL,
  `clintes_idclintes` INT NOT NULL,
  PRIMARY KEY (`idpedidos`),
  CONSTRAINT `fk_pedidos_clintes1`
    FOREIGN KEY (`clintes_idclintes`)
    REFERENCES `vendaProduto`.`clintes` (`idclintes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vendaProduto`.`pedidoitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vendaProduto`.`pedidoitens` (
  `idpedidoitens` INT NOT NULL,
  `qtdade` INT NOT NULL,
  `preco` FLOAT NOT NULL,
  `total` FLOAT NOT NULL,
  `produtos_idprodutos` INT NOT NULL,
  `pedidos_idpedidos` INT NOT NULL,
  PRIMARY KEY (`idpedidoitens`),
  CONSTRAINT `fk_pedidoitens_produtos1`
    FOREIGN KEY (`produtos_idprodutos`)
    REFERENCES `vendaProduto`.`produtos` (`idprodutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidoitens_pedidos1`
    FOREIGN KEY (`pedidos_idpedidos`)
    REFERENCES `vendaProduto`.`pedidos` (`idpedidos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
